micronaut:
  application:
    name: demo
tracing:
  jaeger:
    enabled: true

netty:
  default:
    allocator:
      max-order: 3

logger:
  levels:
    io:
      micronaut:
        http:
          client: TRACE
          server: TRACE